// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' 
show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2RUZT2DbQM0vu5tUdL2Fmr323zYXNQy4',
    appId: '1:734686648700:web:1c0a91fd6703cdffb76cf9',
    messagingSenderId: '734686648700',
    projectId: 'cooking-5135c',
    authDomain: 'cooking-5135c.firebaseapp.com',
    storageBucket: 'cooking-5135c.firebasestorage.app',
    measurementId: 'G-3MX4CR680T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwrVEBKKTzGpp1tSvUQ092yiPqUQiqCLc',
    appId: '1:734686648700:android:b031df162533cc36b76cf9',
    messagingSenderId: '734686648700',
    projectId: 'cooking-5135c',
    storageBucket: 'cooking-5135c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH0a2hzTy0t1L4QYRcdGy8SAJlR6FANNM',
    appId: '1:734686648700:ios:e299075948686574b76cf9',
    messagingSenderId: '734686648700',
    projectId: 'cooking-5135c',
    storageBucket: 'cooking-5135c.firebasestorage.app',
    iosBundleId: 'com.example.cooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH0a2hzTy0t1L4QYRcdGy8SAJlR6FANNM',
    appId: '1:734686648700:ios:e299075948686574b76cf9',
    messagingSenderId: '734686648700',
    projectId: 'cooking-5135c',
    storageBucket: 'cooking-5135c.firebasestorage.app',
    iosBundleId: 'com.example.cooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2RUZT2DbQM0vu5tUdL2Fmr323zYXNQy4',
    appId: '1:734686648700:web:dd527c5681a8a271b76cf9',
    messagingSenderId: '734686648700',
    projectId: 'cooking-5135c',
    authDomain: 'cooking-5135c.firebaseapp.com',
    storageBucket: 'cooking-5135c.firebasestorage.app',
    measurementId: 'G-SN2SD527DZ',
  );
}
